### ISSUE TITLE
Unable to compile native_sorted_set_nif, file doesn't exist

### ISSUE THREAD

**Issue by KaytonFletcher** [discordapp/sorted_set_nif#10]
Nif crate is not generating in the native folder. 

Upon running **mix do deps.get, deps.compile** I receive error 

```
Compiling NIF crate :sorted_set (native/sorted_set_nif)...
could not compile dependency :sorted_set_nif, "mix compile" failed. You can recompile this dependency with "mix deps.compile sorted_set_nif", update it with "mix deps.update sorted_set_nif" or clean it with "mix deps.clean sorted_set_nif"
** (ErlangError) Erlang error: :enoent
    (elixir) lib/system.ex:791: System.cmd("cargo", ["rustc", "--release"], [cd: "/mnt/d/PersonalProjects/Phoenix/MusicBrew/deps/sorted_set_nif/native/sorted_set_nif", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/mnt/d/PersonalProjects/Phoenix/MusicBrew/_build/dev/rustler_crates/sorted_set"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    lib/mix/tasks/compile.rustler.ex:58: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/compile.rustler.ex:14: Mix.Tasks.Compile.Rustler.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:73: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:53: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:24: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
```

and Elixir LS extension in VSCode provides the error

```
an exception was raised:
    ** (RuntimeError) Rust NIF compile error (rustc exit code 1)
        lib/mix/tasks/compile.rustler.ex:67: Mix.Tasks.Compile.Rustler.compile_crate/1
        (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
        lib/mix/tasks/compile.rustler.ex:14: Mix.Tasks.Compile.Rustler.run/1
        (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
        (mix) lib/mix/tasks/compile.all.ex:68: Mix.Tasks.Compile.All.run_compiler/2
        (mix) lib/mix/tasks/compile.all.ex:52: Mix.Tasks.Compile.All.do_compile/4
        (mix) lib/mix/tasks/compile.all.ex:23: anonymous fn/1 in Mix.Tasks.Compile.All.run/
```

Am I missing something?

**Comment by tzumby** [comment]
Just tries this and I think I'm getting a similar error. I think it's the Erlang version based on this:

```
--- stdout
Unsupported Erlang version.
```

**Comment by tzumby** [comment]
Can confirm that it compiles fine with OTP < 22

**Comment by lessless** [comment]
Having the same problem. Probably this project is not maintained.
